### ISSUE TITLE
How can i set this up?

### ISSUE THREAD

**Issue by caisright11** [esabouraud/steamscordbot#2]
I've been following the instructions and have been trying to get this to work: python -m steamscordbot --=<Steam API key> --discord-token=<Discord Bot Token>

Can you please help

**Comment by esabouraud** [comment]
Please ensure you have the [prerequisites](https://github.com/esabouraud/steamscordbot#prerequisites).
Then you have to show what's going wrong in order to get help.

**Comment by caisright11** [comment]
![image](https://user-images.githubusercontent.com/107580385/175618778-5f3a1ca0-e037-4051-a4a7-7a6653688557.png)

**Comment by caisright11** [comment]
![Screenshot 2022-06-24 2 12 16 PM](https://user-images.githubusercontent.com/107580385/175618870-64b8d6a8-1269-42a1-9345-aebf14c2917e.png)

**Comment by esabouraud** [comment]
Just keep it simple to get started, and follow the README.
```
git clone https://github.com/esabouraud/steamscordbot.git
cd steamscordbot
pip install -U -r requirements.txt
python -m steamscordbot --steam-apikey=your_Steam_API_key --discord-token=your_Discord_Bot_Token
```
Once you get this working, hack away ;)

**Comment by caisright11** [comment]
Do I change the stuff in main?

**Comment by esabouraud** [comment]
You sure can.
